# Generated by Django 2.1 on 2018-10-10 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadenuncia', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='idcomentario',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='idpublicion',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='idusuario',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='idusuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fechabaja',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fechacomentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='idcomentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fechaAlta',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fechaBaja',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(default=20180101, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='idpublicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='idusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motivodenuncia',
            name='motivo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='idpublicion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='descripcion',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
        migrations.DeleteModel(
            name='Perfiles',
        ),
        migrations.AddField(
            model_name='denuncias',
            name='idcomentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comentario'),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='idmotivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.MotivoDenuncia'),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='idpublicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
