# Generated by Django 2.1 on 2018-10-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181010_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='idcomentario',
            field=models.AutoField(default=20180801, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(default=20180201, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
