# Generated by Django 2.1 on 2018-10-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181012_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='cuerpocomentario',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
